In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int8')

In [9]:
a.itemsize

1

In [10]:
a.nbytes

3

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a[1,2]

10

In [14]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
a[:, 1]

array([2, 9])

In [17]:
a[0, 1:6:2]

array([2, 4, 6])

In [18]:
a[1,2] = 20

In [19]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 13 14]]


In [22]:
#3d array
b= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
b[0, 1, 1]

5

In [25]:
#0 matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [28]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [29]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
np.random.rand(2,3)

array([[0.42207052, 0.65363455, 0.24030841],
       [0.51108676, 0.68455834, 0.89749173]])

In [35]:
np.random.randint(10, size=(3,3))

array([[1, 6, 3],
       [9, 3, 5],
       [8, 5, 1]])

In [36]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr = np.array([[1,2,3]])
rp1 = np.repeat(arr, 3, axis=0)
print(rp1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
arr = np.ones((5,5), dtype='int32')
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
arr[1:4, 1:4] = np.zeros((3,3), dtype='int32')

In [41]:
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [42]:
arr[2, 2] = 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [43]:
#para copiar un array usamos el metodo copy(), porque sino estaremos copiando el puntero del otro array
#y si cambiamos uno de los dos, el cambio se va a efectuar en ambos
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [45]:
a = np.full((2,3), 2)
b = np.ones((3,2))

In [46]:
print(a)
print(b)

[[2 2 2]
 [2 2 2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [47]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [48]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [49]:
np.max(stats)

6

In [50]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [51]:
after = before.reshape((8,1))
print(before)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [52]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
np.hstack((v1, v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [57]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [58]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [60]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-1]]

array([2, 3, 9])

In [66]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [65]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [68]:
filedata[((filedata > 50) & (filedata < 100))]

array([75, 75, 55, 78, 76, 88])

In [69]:
(~(filedata > 50) & (filedata < 100))
#el NOT es alt+4 '~'

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])